### ISSUE TITLE
make commands work but yield error: "make[1]: *** No rule to make target 'Makefile.*'.  Stop."

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk-console#210]
Most `make` commands show this error during cluster creation.

While the commands end up working, this error may confuse users. Let's get this to go away.

**Comment by willgraf** [comment]
It looks like this issue is from including the build-harness Makefile:

https://github.com/vanvalenlab/kiosk/blob/c5cf1db17494eaee45ccbcf09c5fd3bcb7b331bc/conf/Makefile#L3

Is this something that is really necessary?

**Comment by willgraf** [comment]
Upgrading `build-harness` to version `0.31.0` (the latest version) actually adds further target errors:

<img width="792" alt="Screen Shot 2020-01-16 at 5 57 55 PM" src="https://user-images.githubusercontent.com/7930703/72578086-d301b180-3889-11ea-97d2-0d567cc57034.png">

**Comment by willgraf** [comment]
Investigating further, it seems that the new error message comes directly from the build-harness/Makefile:

https://github.com/cloudposse/build-harness/blob/1a2cd6dbaf4a8242e0ae986d231bdfa53c92e0e2/Makefile#L30

But why is it complaining?

**Comment by osterman** [comment]
@willgraf yes, this is annoying. I think it was introduced with a [recent PR](https://github.com/cloudposse/build-harness/pull/158) from our community. the `-include` should ensure no errors are emitted, but I think the multiple wildcards is messing it up when paths contain a "space" character (or certain versions of `make`)

**Comment by osterman** [comment]
We've merged a fixed and released it.

**Comment by willgraf** [comment]
Awesome! Can confirm version `0.31.1` of the build-harness fixes the additional error from `build-harness-extensions`.

However, I am still seeing the original error (in the title).

**Comment by willgraf** [comment]
This issue seems to be resolved. Unfortunately, I do not understand what has changed to resolve it but I have not seen the error in commits after release `1.1.0`.
